project:
  type: website

website:
  title: "CR-7 GET technical workflow"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About       
        href: about.qmd
      - text: RLIe indicator       
        href: RLIe GET.qmd      
      
format:
  html:
    linestretch: 1.9
    toc-title: "On this page"
    toc: true
    anchor-sections: true
    code-copy: true
    code-overflow: wrap
    css: styles.css
    
    theme:
      light: cosmo

    grid:
      sidebar-width: 350px
      body-width: 1800px
      margin-width: 400px
      
execute: 
  warning: false
  message: false
  
crossref:
  fig-title: '**Figure**'
  fig-labels: arabic
  title-delim: "**:**"
      
freeze: true

editor: visual



